spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/solr?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: '123456'
  data:
    solr:
      host: http://localhost:8080/solr
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  redis:
    ##ip号
    host: 192.168.244.129
    ##端口号
    port: 6379
    ##密码
    password:
    ##数据库的索引
    database: 0
    ##连接超时时间
    timeout: 1000
    jedis:
      pool:
        ##最大的连接数
        max-active: 200
        ##最大的空闲连接
        max-idle: 10
        ##最大的阻塞时间
        max-wait: -1
        ##最小的空闲连接
        min-idle: 0

 ## devtools:
   ## restart:
     ## enabled: true
      ## additional-paths: src/main/java

server:
  port: 8082




